version: '3'

services:

  catalog:
    build: ./Catalog
    ports:
      - "5001:5001"
    volumes:
      - ./Data:/data

  order:
    build: ./Order
    ports:
      - "5002:5002"
    volumes:
      - ./Data:/data
    depends_on:
      - catalog

  frontend:
    build: ./Frontend
    ports:
      - "5000:5000"
    depends_on:
      - catalog
      - order