version: '3'

services:

  catalog:
    build: ./catalog
    ports:
      - "5001:5001"
    volumes:
      - ./data:/data

  order:
    build: ./order
    ports:
      - "5002:5002"

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"